" VUNDLE 
""" viMproved
set nocompatible

""" Required
filetype off

""" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin('~/.vim/bundle')

""" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

call vundle#end()
filetype plugin indent on

" PLUGINS
""" Colorschemes
Plugin 'gregsexton/Muon'
Plugin 'synergistics/anderson.vim'
Plugin 'morhetz/gruvbox'
" Not needed! La elephante and ryuuko xresources mingle extremely well with
" one another. A new era has begun!
Plugin 'synergistics/ryuuko.vim'

""" Option toggling, extra shorthand commands
Plugin 'tpope/vim-unimpaired' 

""" Commenting 
Plugin 'scrooloose/nerdcommenter'

""" Directory tree viewer
Plugin 'scrooloose/nerdtree'

""" Automatic tag closing (parens, angle brackets, quotes, et cetera)
Plugin 'Raimondi/delimitMate'

""" Surrounding tag tool
Plugin 'tpope/vim-surround'

" PLUGIN CONFIG
"" NERDTree
""" Start at start
autocmd VimEnter * :NERDTree | wincmd p

""" Toggle NERDTree
nnoremap <leader>nt :NERDTreeToggle<CR>

" GENERAL
""" Sets number of commands VIM remembers
set history=700

""" Allows external file changes to be auto read 
set autoread

""" Maps leader key to ','
let mapleader = ',' 

""" Faster reloading/editing of vimrc
nmap <silent> <leader>sv :so $MYVIMRC<cr>
nmap <silent> <leader>ev :e $MYVIMRC<cr>

" USER INTERFACE
""" Allows syntax highlighting
syntax on

""" Sets wildmenu on for tab completion
set wildmenu

""" Sets ruler in statusline
set ruler

""" When list is on, set end of line char to ¬
set lcs=eol:¬

""" Current line number shown with surrounding relative numbers
set number
set relativenumber

""" 256 color
set t_Co=256

""" Set colorscheme the following
colorscheme anderson

" TEXT RELATED
""" Sets tab and inserted tab to two spaces
set tabstop=2
set shiftwidth=2
set expandtab

""" Makes indents follow depth and whitespace chars of previous lines
set autoindent
set copyindent

""" Set word wrapping and only explicit line breaks
set wrap

""" Remove smart settings for pasting
set pastetoggle=<leader>p

" SEARCHING
""" Ignores case when searching
set ignorecase

""" If search is all lowercase, ignore case, otherwise, search with case
set smartcase

""" Highlight search matches
set hlsearch

""" Show search matches while typing
set incsearch

""" No highlight search after completed
nnoremap <silent><CR> :let @/ = ""<CR>:call clearmatches()<CR>

" FILES, UNDOS, AND BACKUPS
""" Sets undo history
set undolevels=1000

""" Prevents vim backups, use git instead
set nobackup
set noswapfile

" WINDOWS, BUFFERS, AND TABS
""" Sets buffers to hidden and not inactive state
set hidden

"" Tabs
map <leader>th :tabprevious<CR>
map <leader>tl :tabnext<CR>
map <silent><leader>tm :<C-U>exe "tabmove " . (v:count)<CR> 
map <leader>tn :tabnew<CR>
map <leader>tc :tabclose<CR>
map <leader>to :tabonly<CR>

" EXTRA MAPPINGS/REMAPPINGS
nmap <leader>wsh :w<CR>:sh<CR>
nmap <leader>wqa :wa<CR>:qa<CR>

nmap <leader>w :w!<CR>
nmap <leader>q :q!<CR>

""" Autocenter and consider wrapped lines as seperate ones when moving up and down
nnoremap j gj
nnoremap k gk

nmap 0 ^
