#! /bin/sh

bspc config window_gap 8
bspc config border_width 0

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_by_distance true

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

source ~/dotfiles/bspwm/panel/panel &

# bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a Firefox desktop=^2

# bspc rule -a mplayer2 floating=on
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# Get background up
source ~/.fehbg

# Start compton
compton --config ~/.config/compton/compton.conf -b

