source ~/.zsh/history.zsh

setopt appendhistory extendedglob nomatch notify
unsetopt autocd beep
bindkey -v
zstyle :compinstall filename ~/.zshrc

autoload -Uz compinit
compinit

zstyle ':completion:*' menu select 
setopt completealiases
setopt sh_word_split

export LANG=en_US.UTF-8
